[tool.poetry]
name = "sports-tracker"
version = "0.1.0"
description = ""
authors = ["you@example.com"]

[tool.poetry.dependencies]
python = "^3.10"
streamlit = "*"
pandas = "*"
requests = "*"
supabase = "*"
nba_api = "*"
statsapi = "*"
